### ISSUE TITLE
Only the first 20 workflows of a bucket are displayed in the list

### ISSUE THREAD

**Issue by laurianed** [ow2-proactive/workflow-catalog#26]
If the workflow catalog is open, only the first 20 workflows appear in the list. If new workflows are added, they are displayed. But once the catalog is closed and open again, they don't appear anymore.

**Comment by laurentpellegrino** [comment]
@laurianed What do you mean by _closed and open again_? Is the Workflow Catalog started as an embedded service with the Scheduler or is it started in standalone mode?

**Comment by laurianed** [comment]
@lpellegr I'm talking about the catalog popup into the studio

**Comment by paraita** [comment]
@laurianed, @sophiesongge and I wrote the initial implementation of the Catalog into the Studio. If I remember correctly when the workflow is actually submitted to the catalog, I didn't managed to get the current view to refresh itself with the new workflow, so I also added the workflow manually into the view. Since pagination haven't been implemented yet, if the freshly submitted workflow is the 21th workflow of that bucket, that would result in the workflow to appear in the view, but as soon as you close and re-open the view again, that workflow disappear because of the 20-workflow pagination.
